baseURL: 'https://theruziev.com/'
languageCode: en-us
title: theruziev.com
theme: "archie"
publishDir: docs/
params:
  subtitle: 'cringe-person, night-time dreamer, streetwalker, smalltalker'
  dateFmt: '02.01.2006 15:04'
  useCDN: true
  mode: 'toggle'
  customcss: ["css/custom.css"]
  favicon: "favicon.png"
  social:
    - name: Github
      icon: 'github'
      url: 'https://github.com/theruziev'
    - name: LinkedIn
      icon: 'linkedin'
      url: 'https://www.linkedin.com/in/theruziev/'

markup:
  goldmark:
    renderer:
      unsafe: true

